# coding: utf-8

"""
    Visier Project Management APIs

    Visier APIs for managing and publishing projects

    The version of the OpenAPI document: 22222222.99201.1411
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier.sdk.api.project_management.models.commit_dto import CommitDTO

class TestCommitDTO(unittest.TestCase):
    """CommitDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommitDTO:
        """Test CommitDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommitDTO`
        """
        model = CommitDTO()
        if include_optional:
            return CommitDTO(
                description = '',
                id = '',
                name = ''
            )
        else:
            return CommitDTO(
        )
        """

    def testCommitDTO(self):
        """Test CommitDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
