# coding: utf-8

"""
    Visier Data Out APIs

    Visier APIs for getting data out of Visier, such as aggregate data and data version information.

    The version of the OpenAPI document: 0.99201.1475
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_api_data_out.models.vee_feedback_dto import VeeFeedbackDTO

class TestVeeFeedbackDTO(unittest.TestCase):
    """VeeFeedbackDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VeeFeedbackDTO:
        """Test VeeFeedbackDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VeeFeedbackDTO`
        """
        model = VeeFeedbackDTO()
        if include_optional:
            return VeeFeedbackDTO(
                description = '',
                is_approved = True,
                response = visier_api_data_out.models.vee_response_dto.VeeResponseDTO(
                    chart_url = '', 
                    conversation_state = null, 
                    corrections = [
                        visier_api_data_out.models.vee_corrections_dto.VeeCorrectionsDTO(
                            clarifications = [
                                visier_api_data_out.models.vee_clarification_dto.VeeClarificationDTO(
                                    attributes = [
                                        ''
                                        ], 
                                    dimensions = [
                                        ''
                                        ], 
                                    filters = [
                                        ''
                                        ], 
                                    message = '', 
                                    metrics = [
                                        ''
                                        ], 
                                    questions = [
                                        ''
                                        ], )
                                ], 
                            warning = [
                                'VEE_NO_WARNING'
                                ], )
                        ], 
                    data = null, 
                    narrative = '', 
                    reworded_question = '', 
                    schema = null, 
                    status_code = null, 
                    visual = null, )
            )
        else:
            return VeeFeedbackDTO(
        )
        """

    def testVeeFeedbackDTO(self):
        """Test VeeFeedbackDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
