# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1411
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier.sdk.api.user_management.models.user_group_assigned_for_local_tenant_dto import UserGroupAssignedForLocalTenantDTO

class TestUserGroupAssignedForLocalTenantDTO(unittest.TestCase):
    """UserGroupAssignedForLocalTenantDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserGroupAssignedForLocalTenantDTO:
        """Test UserGroupAssignedForLocalTenantDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserGroupAssignedForLocalTenantDTO`
        """
        model = UserGroupAssignedForLocalTenantDTO()
        if include_optional:
            return UserGroupAssignedForLocalTenantDTO(
                display_name = '',
                user_group_id = ''
            )
        else:
            return UserGroupAssignedForLocalTenantDTO(
        )
        """

    def testUserGroupAssignedForLocalTenantDTO(self):
        """Test UserGroupAssignedForLocalTenantDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
