# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1411
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier.sdk.api.user_management.models.assign_revoke_permissions_request import AssignRevokePermissionsRequest

class TestAssignRevokePermissionsRequest(unittest.TestCase):
    """AssignRevokePermissionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssignRevokePermissionsRequest:
        """Test AssignRevokePermissionsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssignRevokePermissionsRequest`
        """
        model = AssignRevokePermissionsRequest()
        if include_optional:
            return AssignRevokePermissionsRequest(
                permissions = [
                    visier.sdk.api.user_management.models.permission.Permission(
                        permission_id = '', 
                        user_ids = [
                            ''
                            ], )
                    ]
            )
        else:
            return AssignRevokePermissionsRequest(
        )
        """

    def testAssignRevokePermissionsRequest(self):
        """Test AssignRevokePermissionsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
