# coding: utf-8

"""
    Visier User Management APIs

    Visier APIs for managing users within an organization

    The version of the OpenAPI document: 22222222.99201.1411
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier.sdk.api.user_management.models.all_profile_assigned_for_local_tenant_dto import AllProfileAssignedForLocalTenantDTO

class TestAllProfileAssignedForLocalTenantDTO(unittest.TestCase):
    """AllProfileAssignedForLocalTenantDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AllProfileAssignedForLocalTenantDTO:
        """Test AllProfileAssignedForLocalTenantDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AllProfileAssignedForLocalTenantDTO`
        """
        model = AllProfileAssignedForLocalTenantDTO()
        if include_optional:
            return AllProfileAssignedForLocalTenantDTO(
                assigned_profiles = [
                    visier.sdk.api.user_management.models.profile_assigned_for_local_tenant_dto.ProfileAssignedForLocalTenantDTO(
                        additional_capabilities = null, 
                        capabilities = [
                            visier.sdk.api.user_management.models.capabilities_dto.CapabilitiesDTO(
                                access_level = '', 
                                capability = '', 
                                view_level = '', )
                            ], 
                        display_name = '', 
                        profile_id = '', 
                        validity_end_time = '', 
                        validity_start_time = '', )
                    ]
            )
        else:
            return AllProfileAssignedForLocalTenantDTO(
        )
        """

    def testAllProfileAssignedForLocalTenantDTO(self):
        """Test AllProfileAssignedForLocalTenantDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
