# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.2960
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from visier_platform_sdk.models.data_export_connector_credential_validation_request_with_id import DataExportConnectorCredentialValidationRequestWithId
from visier_platform_sdk.models.data_export_connector_credential_validation_request_with_parameters import DataExportConnectorCredentialValidationRequestWithParameters
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

DATAEXPORTCONNECTORCREDENTIALVALIDATIONREQUEST_ONE_OF_SCHEMAS = ["DataExportConnectorCredentialValidationRequestWithId", "DataExportConnectorCredentialValidationRequestWithParameters"]

class DataExportConnectorCredentialValidationRequest(BaseModel):
    """
    DataExportConnectorCredentialValidationRequest
    """
    # data type: DataExportConnectorCredentialValidationRequestWithId
    oneof_schema_1_validator: Optional[DataExportConnectorCredentialValidationRequestWithId] = None
    # data type: DataExportConnectorCredentialValidationRequestWithParameters
    oneof_schema_2_validator: Optional[DataExportConnectorCredentialValidationRequestWithParameters] = None
    actual_instance: Optional[Union[DataExportConnectorCredentialValidationRequestWithId, DataExportConnectorCredentialValidationRequestWithParameters]] = None
    one_of_schemas: Set[str] = { "DataExportConnectorCredentialValidationRequestWithId", "DataExportConnectorCredentialValidationRequestWithParameters" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            # Because our oneof-type models do not initialize in such a way that simply passing them into the constructor will do it much good, we need to follow a pattern similar to from_json
            actual_instance = None
            error_messages = []
            match = 0

            # attempt to construct DataExportConnectorCredentialValidationRequestWithId using arguments provided
            try:
                actual_instance = DataExportConnectorCredentialValidationRequestWithId(**kwargs)
                match += 1
            except (ValidationError, ValueError) as e:
                error_messages.append(str(e))
            # attempt to construct DataExportConnectorCredentialValidationRequestWithParameters using arguments provided
            try:
                actual_instance = DataExportConnectorCredentialValidationRequestWithParameters(**kwargs)
                match += 1
            except (ValidationError, ValueError) as e:
                error_messages.append(str(e))

            if match > 1:
                # more than 1 match
                raise ValueError("Multiple matches found when constructing actual instance of DataExportConnectorCredentialValidationRequest with oneOf schemas: DataExportConnectorCredentialValidationRequestWithId, DataExportConnectorCredentialValidationRequestWithParameters. Details: " + ", ".join(error_messages))
            elif match == 0:
                # no match
                raise ValueError("No match found when constructing actual instance of DataExportConnectorCredentialValidationRequest with oneOf schemas: DataExportConnectorCredentialValidationRequestWithId, DataExportConnectorCredentialValidationRequestWithParameters. Details: " + ", ".join(error_messages))
            else:
                super().__init__(actual_instance=actual_instance)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = DataExportConnectorCredentialValidationRequest.model_construct()
        error_messages = []
        match = 0
        # validate data type: DataExportConnectorCredentialValidationRequestWithId
        if not isinstance(v, DataExportConnectorCredentialValidationRequestWithId):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DataExportConnectorCredentialValidationRequestWithId`")
        else:
            match += 1
        # validate data type: DataExportConnectorCredentialValidationRequestWithParameters
        if not isinstance(v, DataExportConnectorCredentialValidationRequestWithParameters):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DataExportConnectorCredentialValidationRequestWithParameters`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in DataExportConnectorCredentialValidationRequest with oneOf schemas: DataExportConnectorCredentialValidationRequestWithId, DataExportConnectorCredentialValidationRequestWithParameters. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in DataExportConnectorCredentialValidationRequest with oneOf schemas: DataExportConnectorCredentialValidationRequestWithId, DataExportConnectorCredentialValidationRequestWithParameters. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into DataExportConnectorCredentialValidationRequestWithId
        try:
            instance.actual_instance = DataExportConnectorCredentialValidationRequestWithId.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DataExportConnectorCredentialValidationRequestWithParameters
        try:
            instance.actual_instance = DataExportConnectorCredentialValidationRequestWithParameters.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into DataExportConnectorCredentialValidationRequest with oneOf schemas: DataExportConnectorCredentialValidationRequestWithId, DataExportConnectorCredentialValidationRequestWithParameters. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into DataExportConnectorCredentialValidationRequest with oneOf schemas: DataExportConnectorCredentialValidationRequestWithId, DataExportConnectorCredentialValidationRequestWithParameters. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], DataExportConnectorCredentialValidationRequestWithId, DataExportConnectorCredentialValidationRequestWithParameters]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


