# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from visier_platform_sdk.models.servicing_v2_objectconfiguration_synonym_list_dto import ServicingV2ObjectconfigurationSynonymListDTO
from typing import Optional, Set
from typing_extensions import Self

class ServicingV2ObjectconfigurationBasicInformationDTO(BaseModel):
    """
    Fields that identify and describe the object, such as its display name, description, and explanation.
    """ # noqa: E501
    display_name: Optional[StrictStr] = Field(default=None, description="The user-friendly name for the object.", alias="displayName")
    short_display_name: Optional[StrictStr] = Field(default=None, description="A shortened version of the display name. If the object is visible in the solution experience, this name is displayed in visualization titles.", alias="shortDisplayName")
    description: Optional[StrictStr] = Field(default=None, description="A short description of the object. Descriptions provide in-context help for your users while working in Visier.")
    explanation: Optional[StrictStr] = Field(default=None, description="A longer description of the object that typically includes a definition, calculation details, and other guidance about how to use the object.")
    designer_notes: Optional[StrictStr] = Field(default=None, description="An admin-only description of the object that provides design-specific information or considerations.", alias="designerNotes")
    synonym_list: Optional[ServicingV2ObjectconfigurationSynonymListDTO] = Field(default=None, description="Alternative words or phrases for the object.", alias="synonymList")
    __properties: ClassVar[List[str]] = ["displayName", "shortDisplayName", "description", "explanation", "designerNotes", "synonymList"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServicingV2ObjectconfigurationBasicInformationDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of synonym_list
        if self.synonym_list:
            _dict['synonymList'] = self.synonym_list.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServicingV2ObjectconfigurationBasicInformationDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "displayName": obj.get("displayName"),
            "shortDisplayName": obj.get("shortDisplayName"),
            "description": obj.get("description"),
            "explanation": obj.get("explanation"),
            "designerNotes": obj.get("designerNotes"),
            "synonymList": ServicingV2ObjectconfigurationSynonymListDTO.from_dict(obj["synonymList"]) if obj.get("synonymList") is not None else None
        })
        return _obj


