# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.2451
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from visier_platform_sdk.models.custom_member_set_selection_dto import CustomMemberSetSelectionDTO
from visier_platform_sdk.models.preset_member_set_selection_dto import PresetMemberSetSelectionDTO
from typing import Optional, Set
from typing_extensions import Self

class SubjectMemberSetParameterValueDTO(BaseModel):
    """
    The value for a metric subject member set parameter.
    """ # noqa: E501
    parameter_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the metric subject member set parameter.", alias="parameterId")
    custom_selection: Optional[CustomMemberSetSelectionDTO] = Field(default=None, alias="customSelection")
    preset_selection: Optional[PresetMemberSetSelectionDTO] = Field(default=None, alias="presetSelection")
    __properties: ClassVar[List[str]] = ["parameterId", "customSelection", "presetSelection"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubjectMemberSetParameterValueDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of custom_selection
        if self.custom_selection:
            _dict['customSelection'] = self.custom_selection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of preset_selection
        if self.preset_selection:
            _dict['presetSelection'] = self.preset_selection.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubjectMemberSetParameterValueDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "parameterId": obj.get("parameterId"),
            "customSelection": CustomMemberSetSelectionDTO.from_dict(obj["customSelection"]) if obj.get("customSelection") is not None else None,
            "presetSelection": PresetMemberSetSelectionDTO.from_dict(obj["presetSelection"]) if obj.get("presetSelection") is not None else None
        })
        return _obj


