# coding: utf-8

# flake8: noqa
"""
    Visier Analytic Model APIs

    Visier APIs for retrieving and configuring your analytic model in Visier.

    The version of the OpenAPI document: 22222222.99201.1793
    Contact: alpine@visier.com

    Please note that this SDK is currently in beta.
    Functionality and behavior may change in future releases.
    We encourage you to provide feedback and report any issues encountered during your use.
"""  # noqa: E501


# import models into model package
from visier_api_analytic_model.models.dataservices_common_dimension_member_reference_dto import DataservicesCommonDimensionMemberReferenceDTO
from visier_api_analytic_model.models.dataservices_common_member_values_dto import DataservicesCommonMemberValuesDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_aggregation_type_option_dto import DataservicesDatamodelTransfersAggregationTypeOptionDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_aggregation_type_parameter_dto import DataservicesDatamodelTransfersAggregationTypeParameterDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_analytic_object_dto import DataservicesDatamodelTransfersAnalyticObjectDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_analytic_objects_dto import DataservicesDatamodelTransfersAnalyticObjectsDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_currencies_dto import DataservicesDatamodelTransfersCurrenciesDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_currency_dto import DataservicesDatamodelTransfersCurrencyDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_currency_rate_dto import DataservicesDatamodelTransfersCurrencyRateDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_currency_rates_dto import DataservicesDatamodelTransfersCurrencyRatesDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_dimension_dto import DataservicesDatamodelTransfersDimensionDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_dimension_mapping_validation_dto import DataservicesDatamodelTransfersDimensionMappingValidationDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_dimension_mapping_validation_execution_dto import DataservicesDatamodelTransfersDimensionMappingValidationExecutionDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_dimension_reference_dto import DataservicesDatamodelTransfersDimensionReferenceDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_dimensions_dto import DataservicesDatamodelTransfersDimensionsDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_level_dto import DataservicesDatamodelTransfersLevelDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_member_dto import DataservicesDatamodelTransfersMemberDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_member_parameter_definition_dto import DataservicesDatamodelTransfersMemberParameterDefinitionDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_members_dto import DataservicesDatamodelTransfersMembersDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_metric_dto import DataservicesDatamodelTransfersMetricDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_metrics_dto import DataservicesDatamodelTransfersMetricsDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_numeric_parameter_definition_dto import DataservicesDatamodelTransfersNumericParameterDefinitionDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_object_reference_dto import DataservicesDatamodelTransfersObjectReferenceDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_parameter_definition_dto import DataservicesDatamodelTransfersParameterDefinitionDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_plan_parameter_definition_dto import DataservicesDatamodelTransfersPlanParameterDefinitionDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_planning_concept_filter_context_dto import DataservicesDatamodelTransfersPlanningConceptFilterContextDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_planning_hierarchy_filter_context_dto import DataservicesDatamodelTransfersPlanningHierarchyFilterContextDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_planning_model_dto import DataservicesDatamodelTransfersPlanningModelDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_planning_models_dto import DataservicesDatamodelTransfersPlanningModelsDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_planning_plan_context_dto import DataservicesDatamodelTransfersPlanningPlanContextDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_planning_plan_dto import DataservicesDatamodelTransfersPlanningPlanDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_planning_plans_dto import DataservicesDatamodelTransfersPlanningPlansDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_population_configuration_dto import DataservicesDatamodelTransfersPopulationConfigurationDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_prediction_dto import DataservicesDatamodelTransfersPredictionDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_predictions_dto import DataservicesDatamodelTransfersPredictionsDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_properties_dto import DataservicesDatamodelTransfersPropertiesDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_property_dto import DataservicesDatamodelTransfersPropertyDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_property_reference_dto import DataservicesDatamodelTransfersPropertyReferenceDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_scenario_or_snapshot_dto import DataservicesDatamodelTransfersScenarioOrSnapshotDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_selection_concept_dto import DataservicesDatamodelTransfersSelectionConceptDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_selection_concepts_dto import DataservicesDatamodelTransfersSelectionConceptsDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_tag_map_element_dto import DataservicesDatamodelTransfersTagMapElementDTO
from visier_api_analytic_model.models.dataservices_datamodel_transfers_validity_range_dto import DataservicesDatamodelTransfersValidityRangeDTO
from visier_api_analytic_model.models.designer_api_transfers_analytic_object_filter_dto import DesignerApiTransfersAnalyticObjectFilterDTO
from visier_api_analytic_model.models.designer_api_transfers_calculation_concept_configuration_dto import DesignerApiTransfersCalculationConceptConfigurationDTO
from visier_api_analytic_model.models.designer_api_transfers_calculation_concept_configuration_map_dto import DesignerApiTransfersCalculationConceptConfigurationMapDTO
from visier_api_analytic_model.models.designer_api_transfers_calculation_concept_dto import DesignerApiTransfersCalculationConceptDTO
from visier_api_analytic_model.models.designer_api_transfers_calculation_concept_list_dto import DesignerApiTransfersCalculationConceptListDTO
from visier_api_analytic_model.models.designer_api_transfers_concept_configuration_result_dto import DesignerApiTransfersConceptConfigurationResultDTO
from visier_api_analytic_model.models.designer_api_transfers_dimension_filter_dto import DesignerApiTransfersDimensionFilterDTO
from visier_api_analytic_model.models.designer_api_transfers_dimension_member_dto import DesignerApiTransfersDimensionMemberDTO
from visier_api_analytic_model.models.designer_api_transfers_perspective_configuration_dto import DesignerApiTransfersPerspectiveConfigurationDTO
from visier_api_analytic_model.models.designer_api_transfers_perspective_node_dto import DesignerApiTransfersPerspectiveNodeDTO
from visier_api_analytic_model.models.designer_api_transfers_selection_concept_configuration_dto import DesignerApiTransfersSelectionConceptConfigurationDTO
from visier_api_analytic_model.models.designer_api_transfers_selection_concept_configuration_map_dto import DesignerApiTransfersSelectionConceptConfigurationMapDTO
from visier_api_analytic_model.models.designer_api_transfers_selection_concept_dto import DesignerApiTransfersSelectionConceptDTO
from visier_api_analytic_model.models.designer_api_transfers_selection_concept_list_dto import DesignerApiTransfersSelectionConceptListDTO
from visier_api_analytic_model.models.planning_transfers_get_plan_list_response_dto import PlanningTransfersGetPlanListResponseDTO
from visier_api_analytic_model.models.planning_transfers_plan_data_load_error_dto import PlanningTransfersPlanDataLoadErrorDTO
from visier_api_analytic_model.models.planning_transfers_plan_info_dto import PlanningTransfersPlanInfoDTO
from visier_api_analytic_model.models.planning_transfers_plan_item_dto import PlanningTransfersPlanItemDTO
from visier_api_analytic_model.models.planning_transfers_plan_schema_dto import PlanningTransfersPlanSchemaDTO
from visier_api_analytic_model.models.planning_transfers_plan_segment_level_dto import PlanningTransfersPlanSegmentLevelDTO
from visier_api_analytic_model.models.planning_transfers_plan_segment_level_member_dto import PlanningTransfersPlanSegmentLevelMemberDTO
from visier_api_analytic_model.models.planning_transfers_plan_segment_level_member_list_dto import PlanningTransfersPlanSegmentLevelMemberListDTO
from visier_api_analytic_model.models.planning_transfers_plan_time_period_dto import PlanningTransfersPlanTimePeriodDTO
from visier_api_analytic_model.models.planning_transfers_plan_with_schema_dto import PlanningTransfersPlanWithSchemaDTO
from visier_api_analytic_model.models.planning_transfers_scenario_info_dto import PlanningTransfersScenarioInfoDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_calculated_property_type_dto import ServicingPublicapiObjectconfigurationCalculatedPropertyTypeDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_dependent_dto import ServicingPublicapiObjectconfigurationDependentDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_dimension_change_definition_dto import ServicingPublicapiObjectconfigurationDimensionChangeDefinitionDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_dimension_change_definitions_by_tenant_dto import ServicingPublicapiObjectconfigurationDimensionChangeDefinitionsByTenantDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_dimensions_change_definitions_dto import ServicingPublicapiObjectconfigurationDimensionsChangeDefinitionsDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_object_change_failure_dto import ServicingPublicapiObjectconfigurationObjectChangeFailureDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_object_change_success_dto import ServicingPublicapiObjectconfigurationObjectChangeSuccessDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_objects_bulk_change_response_dto import ServicingPublicapiObjectconfigurationObjectsBulkChangeResponseDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_properties_change_definitions_dto import ServicingPublicapiObjectconfigurationPropertiesChangeDefinitionsDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_properties_delete_definitions_dto import ServicingPublicapiObjectconfigurationPropertiesDeleteDefinitionsDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_property_bulk_delete_response_dto import ServicingPublicapiObjectconfigurationPropertyBulkDeleteResponseDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_property_change_definition_dto import ServicingPublicapiObjectconfigurationPropertyChangeDefinitionDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_property_change_definitions_by_tenant_dto import ServicingPublicapiObjectconfigurationPropertyChangeDefinitionsByTenantDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_property_delete_definitions_by_tenant_dto import ServicingPublicapiObjectconfigurationPropertyDeleteDefinitionsByTenantDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_property_delete_failure_dto import ServicingPublicapiObjectconfigurationPropertyDeleteFailureDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_property_delete_success_dto import ServicingPublicapiObjectconfigurationPropertyDeleteSuccessDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_property_type_dto import ServicingPublicapiObjectconfigurationPropertyTypeDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_simple_property_type_dto import ServicingPublicapiObjectconfigurationSimplePropertyTypeDTO
from visier_api_analytic_model.models.servicing_publicapi_objectconfiguration_tags_dto import ServicingPublicapiObjectconfigurationTagsDTO
from visier_api_analytic_model.models.status import Status
