# coding: utf-8

"""
    Visier Public Direct Data Intake APIs

    Visier APIs for uploading already transformed data files directly to target objects in Visier.

    The version of the OpenAPI document: 22222222.99201.1411
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier.sdk.api.direct_data_intake.models.direct_data_job_config_dto import DirectDataJobConfigDTO

class TestDirectDataJobConfigDTO(unittest.TestCase):
    """DirectDataJobConfigDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DirectDataJobConfigDTO:
        """Test DirectDataJobConfigDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DirectDataJobConfigDTO`
        """
        model = DirectDataJobConfigDTO()
        if include_optional:
            return DirectDataJobConfigDTO(
                extend_objects = [
                    ''
                    ],
                supplemental_mode = 'UNCHANGED'
            )
        else:
            return DirectDataJobConfigDTO(
        )
        """

    def testDirectDataJobConfigDTO(self):
        """Test DirectDataJobConfigDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
