# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.2984
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.api.plan_events_api import PlanEventsApi


class TestPlanEventsApi(unittest.TestCase):
    """PlanEventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlanEventsApi()

    def tearDown(self) -> None:
        pass

    def test_get_event(self) -> None:
        """Test case for get_event

        Retrieve a planning event
        """
        pass

    def test_get_events(self) -> None:
        """Test case for get_events

        Retrieve planning events
        """
        pass


if __name__ == '__main__':
    unittest.main()
