# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.2960
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import visier_platform_sdk.models
from visier_platform_sdk.models.data_export_connector_credential_parameters import DataExportConnectorCredentialParameters

class TestDataExportConnectorCredentialParameters(unittest.TestCase):
    """DataExportConnectorCredentialParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_DataExportConnectorCredentialParametersWithDatabricks_instance(self, include_optional) -> DataExportConnectorCredentialParameters:
        """Test DataExportConnectorCredentialParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """

        if include_optional:
            return visier_platform_sdk.models.data_export_connector_credential_parameters.DataExportConnectorCredentialParameters(databricks=visier_platform_sdk.models.databricks_credential_parameters.DatabricksCredentialParameters())
        else:
            return DataExportConnectorCredentialParameters(
            )

    def make_DataExportConnectorCredentialParametersWithSnowflake_instance(self, include_optional) -> DataExportConnectorCredentialParameters:
        """Test DataExportConnectorCredentialParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """

        if include_optional:
            return visier_platform_sdk.models.data_export_connector_credential_parameters.DataExportConnectorCredentialParameters(snowflake=visier_platform_sdk.models.snowflake_credential_parameters.SnowflakeCredentialParameters())
        else:
            return DataExportConnectorCredentialParameters(
            )


    def testDataExportConnectorCredentialParameters(self):
        """Test DataExportConnectorCredentialParameters"""

        def validate_instance(instance):
            DataExportConnectorCredentialParameters.model_validate(instance)
            instance_deserialized = DataExportConnectorCredentialParameters.from_dict(instance.to_dict())
            assert instance == instance_deserialized

        # Skipping these tests until such time that we can initialize required arguments only
        #inst_req_only = self.make_DataExportConnectorCredentialParametersWithDatabricks_instance(include_optional=False)
        #validate_instance(inst_req_only)

        inst_req_and_optional = self.make_DataExportConnectorCredentialParametersWithDatabricks_instance(include_optional=True)
        validate_instance(inst_req_and_optional)

        # Skipping these tests until such time that we can initialize required arguments only
        #inst_req_only = self.make_DataExportConnectorCredentialParametersWithSnowflake_instance(include_optional=False)
        #validate_instance(inst_req_only)

        inst_req_and_optional = self.make_DataExportConnectorCredentialParametersWithSnowflake_instance(include_optional=True)
        validate_instance(inst_req_and_optional)


if __name__ == '__main__':
    unittest.main()
