# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.2341
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import visier_platform_sdk.models
from visier_platform_sdk.models.product_versions_update_response_dto import ProductVersionsUpdateResponseDTO

class TestProductVersionsUpdateResponseDTO(unittest.TestCase):
    """ProductVersionsUpdateResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductVersionsUpdateResponseDTO:
        """Test ProductVersionsUpdateResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """

        if include_optional:
            return ProductVersionsUpdateResponseDTO(
                successes = [
                    visier_platform_sdk.models.product_versions_update_successful_tenant_response_dto.ProductVersionsUpdateSuccessfulTenantResponseDTO(
                        product_id = '', 
                        version = '', 
                        tenant_codes = [
                            ''
                            ], )
                    ],
                failures = [
                    visier_platform_sdk.models.product_versions_update_failure_tenant_response_dto.ProductVersionsUpdateFailureTenantResponseDTO(
                        product_id = '', 
                        version = '', 
                        tenant_codes = [
                            ''
                            ], 
                        message = '', )
                    ]
            )
        else:
            return ProductVersionsUpdateResponseDTO(
        )

    def testProductVersionsUpdateResponseDTO(self):
        """Test ProductVersionsUpdateResponseDTO"""
        def validate_instance(instance):
            ProductVersionsUpdateResponseDTO.model_validate(inst_req_only)
            instance_deserialized = ProductVersionsUpdateResponseDTO.from_dict(instance.to_dict())
            assert instance == instance_deserialized

        inst_req_only = self.make_instance(include_optional=False)
        validate_instance(inst_req_only)

        inst_req_and_optional = self.make_instance(include_optional=True)
        validate_instance(inst_req_and_optional)

if __name__ == '__main__':
    unittest.main()
