# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.analysis_common_vee_response_schema_reference_dto import AnalysisCommonVeeResponseSchemaReferenceDTO

class TestAnalysisCommonVeeResponseSchemaReferenceDTO(unittest.TestCase):
    """AnalysisCommonVeeResponseSchemaReferenceDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalysisCommonVeeResponseSchemaReferenceDTO:
        """Test AnalysisCommonVeeResponseSchemaReferenceDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalysisCommonVeeResponseSchemaReferenceDTO`
        """
        model = AnalysisCommonVeeResponseSchemaReferenceDTO()
        if include_optional:
            return AnalysisCommonVeeResponseSchemaReferenceDTO(
                name = '',
                paths = [
                    ''
                    ]
            )
        else:
            return AnalysisCommonVeeResponseSchemaReferenceDTO(
        )
        """

    def testAnalysisCommonVeeResponseSchemaReferenceDTO(self):
        """Test AnalysisCommonVeeResponseSchemaReferenceDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
