# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.dv_export_status import DvExportStatus

class TestDvExportStatus(unittest.TestCase):
    """DvExportStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DvExportStatus:
        """Test DvExportStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DvExportStatus`
        """
        model = DvExportStatus()
        if include_optional:
            return DvExportStatus(
                localized_message = '',
                error_code = '',
                message = '',
                rci = '',
                user_error = True
            )
        else:
            return DvExportStatus(
        )
        """

    def testDvExportStatus(self):
        """Test DvExportStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
