# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.dataservices_datamodel_object_reference_dto import DataservicesDatamodelObjectReferenceDTO

class TestDataservicesDatamodelObjectReferenceDTO(unittest.TestCase):
    """DataservicesDatamodelObjectReferenceDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataservicesDatamodelObjectReferenceDTO:
        """Test DataservicesDatamodelObjectReferenceDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataservicesDatamodelObjectReferenceDTO`
        """
        model = DataservicesDatamodelObjectReferenceDTO()
        if include_optional:
            return DataservicesDatamodelObjectReferenceDTO(
                id = '',
                display_name = '',
                description = '',
                from_object = '',
                to_object = '',
                type = 'SUBJECT_REFERENCE',
                is_strong_reference = True
            )
        else:
            return DataservicesDatamodelObjectReferenceDTO(
        )
        """

    def testDataservicesDatamodelObjectReferenceDTO(self):
        """Test DataservicesDatamodelObjectReferenceDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
