# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.dataservices_datamodel_planning_plan_dto import DataservicesDatamodelPlanningPlanDTO

class TestDataservicesDatamodelPlanningPlanDTO(unittest.TestCase):
    """DataservicesDatamodelPlanningPlanDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataservicesDatamodelPlanningPlanDTO:
        """Test DataservicesDatamodelPlanningPlanDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataservicesDatamodelPlanningPlanDTO`
        """
        model = DataservicesDatamodelPlanningPlanDTO()
        if include_optional:
            return DataservicesDatamodelPlanningPlanDTO(
                id = '',
                name = '',
                subject_id = '',
                default_contexts = [
                    visier_platform_sdk.models.dataservices/datamodel/planning_plan_context_dto.dataservices.datamodel.PlanningPlanContextDTO(
                        hierarchy_filter_context = None, 
                        concept_filter_context = None, )
                    ],
                plan_dimension_ids = [
                    ''
                    ],
                scenarios = [
                    visier_platform_sdk.models.dataservices/datamodel/scenario_or_snapshot_dto.dataservices.datamodel.ScenarioOrSnapshotDTO(
                        id = '', 
                        display_name = '', )
                    ],
                snapshots = [
                    visier_platform_sdk.models.dataservices/datamodel/scenario_or_snapshot_dto.dataservices.datamodel.ScenarioOrSnapshotDTO(
                        id = '', 
                        display_name = '', )
                    ]
            )
        else:
            return DataservicesDatamodelPlanningPlanDTO(
        )
        """

    def testDataservicesDatamodelPlanningPlanDTO(self):
        """Test DataservicesDatamodelPlanningPlanDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
