# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.admin_tenant_detail_apidto import AdminTenantDetailAPIDTO

class TestAdminTenantDetailAPIDTO(unittest.TestCase):
    """AdminTenantDetailAPIDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminTenantDetailAPIDTO:
        """Test AdminTenantDetailAPIDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminTenantDetailAPIDTO`
        """
        model = AdminTenantDetailAPIDTO()
        if include_optional:
            return AdminTenantDetailAPIDTO(
                tenant_code = '',
                tenant_display_name = '',
                status = '',
                provision_date = '',
                current_data_version = '',
                data_version_date = '',
                modules = [
                    visier_platform_sdk.models.designer/tenant_module_dto.designer.TenantModuleDTO(
                        display_name = '', 
                        symbol_name = '', 
                        module_settings = None, )
                    ],
                industry_code = 56,
                can_administer_other_tenants = True,
                embeddable_domains = [
                    ''
                    ],
                custom_properties = [
                    visier_platform_sdk.models.admin/custom_tenant_property_dto.admin.CustomTenantPropertyDTO(
                        key = '', 
                        value = '', )
                    ],
                sso_instance_issuers = [
                    ''
                    ],
                vanity_url_name = '',
                allowed_o_auth_idp_url_domains = [
                    ''
                    ]
            )
        else:
            return AdminTenantDetailAPIDTO(
        )
        """

    def testAdminTenantDetailAPIDTO(self):
        """Test AdminTenantDetailAPIDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
