# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.admin_user_groups_delete_request_dto import AdminUserGroupsDeleteRequestDTO

class TestAdminUserGroupsDeleteRequestDTO(unittest.TestCase):
    """AdminUserGroupsDeleteRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminUserGroupsDeleteRequestDTO:
        """Test AdminUserGroupsDeleteRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminUserGroupsDeleteRequestDTO`
        """
        model = AdminUserGroupsDeleteRequestDTO()
        if include_optional:
            return AdminUserGroupsDeleteRequestDTO(
                user_groups = [
                    visier_platform_sdk.models.admin/user_group_delete_dto.admin.UserGroupDeleteDTO(
                        tenant_code = '', 
                        user_group_id = '', 
                        project_id = '', )
                    ]
            )
        else:
            return AdminUserGroupsDeleteRequestDTO(
        )
        """

    def testAdminUserGroupsDeleteRequestDTO(self):
        """Test AdminUserGroupsDeleteRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
