# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.dataservices_query_key_group_filter_dto import DataservicesQueryKeyGroupFilterDTO

class TestDataservicesQueryKeyGroupFilterDTO(unittest.TestCase):
    """DataservicesQueryKeyGroupFilterDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataservicesQueryKeyGroupFilterDTO:
        """Test DataservicesQueryKeyGroupFilterDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataservicesQueryKeyGroupFilterDTO`
        """
        model = DataservicesQueryKeyGroupFilterDTO()
        if include_optional:
            return DataservicesQueryKeyGroupFilterDTO(
                filters = [
                    visier_platform_sdk.models.dataservices/query/key_group_filter_item_dto.dataservices.query.KeyGroupFilterItemDTO(
                        formula = '', 
                        selection_concept = None, 
                        member_set = None, )
                    ]
            )
        else:
            return DataservicesQueryKeyGroupFilterDTO(
        )
        """

    def testDataservicesQueryKeyGroupFilterDTO(self):
        """Test DataservicesQueryKeyGroupFilterDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
