# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.servicing_v2_objectconfiguration_process_concept_outcome_list_dto import ServicingV2ObjectconfigurationProcessConceptOutcomeListDTO

class TestServicingV2ObjectconfigurationProcessConceptOutcomeListDTO(unittest.TestCase):
    """ServicingV2ObjectconfigurationProcessConceptOutcomeListDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServicingV2ObjectconfigurationProcessConceptOutcomeListDTO:
        """Test ServicingV2ObjectconfigurationProcessConceptOutcomeListDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServicingV2ObjectconfigurationProcessConceptOutcomeListDTO`
        """
        model = ServicingV2ObjectconfigurationProcessConceptOutcomeListDTO()
        if include_optional:
            return ServicingV2ObjectconfigurationProcessConceptOutcomeListDTO(
                outcomes = [
                    visier_platform_sdk.models.servicing/v2/objectconfiguration/process_concept_outcome_dto.servicing.v2.objectconfiguration.ProcessConceptOutcomeDTO(
                        uuid = '', 
                        object_name = '', 
                        basic_information = None, 
                        outcome_semantic = 'Success', 
                        mapped_member_list = None, )
                    ]
            )
        else:
            return ServicingV2ObjectconfigurationProcessConceptOutcomeListDTO(
        )
        """

    def testServicingV2ObjectconfigurationProcessConceptOutcomeListDTO(self):
        """Test ServicingV2ObjectconfigurationProcessConceptOutcomeListDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
