# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.admin_target_project_for_tenants_list_dto import AdminTargetProjectForTenantsListDTO

class TestAdminTargetProjectForTenantsListDTO(unittest.TestCase):
    """AdminTargetProjectForTenantsListDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminTargetProjectForTenantsListDTO:
        """Test AdminTargetProjectForTenantsListDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminTargetProjectForTenantsListDTO`
        """
        model = AdminTargetProjectForTenantsListDTO()
        if include_optional:
            return AdminTargetProjectForTenantsListDTO(
                target_project_for_tenants = [
                    visier_platform_sdk.models.admin/target_project_for_tenant_dto.admin.TargetProjectForTenantDTO(
                        tenant_code = '', 
                        project_id = '', )
                    ]
            )
        else:
            return AdminTargetProjectForTenantsListDTO(
        )
        """

    def testAdminTargetProjectForTenantsListDTO(self):
        """Test AdminTargetProjectForTenantsListDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
