# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.3221
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import visier_platform_sdk.models
from visier_platform_sdk.models.get_pilot_features_response_dto import GetPilotFeaturesResponseDTO

class TestGetPilotFeaturesResponseDTO(unittest.TestCase):
    """GetPilotFeaturesResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPilotFeaturesResponseDTO:
        """Test GetPilotFeaturesResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """

        if include_optional:
            return GetPilotFeaturesResponseDTO(
                features = [
                    visier_platform_sdk.models.pilot_feature_dto.PilotFeatureDTO(
                        feature_key = '', 
                        display_name = '', 
                        description = '', 
                        type = 'PILOT_FEATURE_TYPE_UNSPECIFIED', 
                        release_date = '', 
                        learn_more_url = '', 
                        user_config = None, 
                        tenant_config = None, )
                    ]
            )
        else:
            return GetPilotFeaturesResponseDTO(
            )

    def testGetPilotFeaturesResponseDTO(self):
        """Test GetPilotFeaturesResponseDTO"""

        def validate_instance(instance):
            GetPilotFeaturesResponseDTO.model_validate(instance)
            instance_deserialized = GetPilotFeaturesResponseDTO.from_dict(instance.to_dict())
            assert instance == instance_deserialized

        inst_req_only = self.make_instance(include_optional=False)
        validate_instance(inst_req_only)

        inst_req_and_optional = self.make_instance(include_optional=True)
        validate_instance(inst_req_and_optional)


if __name__ == '__main__':
    unittest.main()
