# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.servicing_users_api_response_dto import ServicingUsersAPIResponseDTO

class TestServicingUsersAPIResponseDTO(unittest.TestCase):
    """ServicingUsersAPIResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServicingUsersAPIResponseDTO:
        """Test ServicingUsersAPIResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServicingUsersAPIResponseDTO`
        """
        model = ServicingUsersAPIResponseDTO()
        if include_optional:
            return ServicingUsersAPIResponseDTO(
                successes = [
                    visier_platform_sdk.models.servicing/users_api_success_dto.servicing.UsersAPISuccessDTO(
                        user_id = '', 
                        username = '', 
                        display_name = '', 
                        employee_id = '', 
                        account_enabled = '', 
                        email = '', )
                    ],
                failures = [
                    visier_platform_sdk.models.servicing/users_api_failure_dto.servicing.UsersAPIFailureDTO(
                        user_id = '', 
                        user_name = '', 
                        display_name = '', 
                        error = None, )
                    ]
            )
        else:
            return ServicingUsersAPIResponseDTO(
        )
        """

    def testServicingUsersAPIResponseDTO(self):
        """Test ServicingUsersAPIResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
