# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.data_in_receiving_job_status_response import DataInReceivingJobStatusResponse

class TestDataInReceivingJobStatusResponse(unittest.TestCase):
    """DataInReceivingJobStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataInReceivingJobStatusResponse:
        """Test DataInReceivingJobStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataInReceivingJobStatusResponse`
        """
        model = DataInReceivingJobStatusResponse()
        if include_optional:
            return DataInReceivingJobStatusResponse(
                job_id = '',
                status = '',
                parent_job_id = '',
                parent_tenant_code = '',
                receiving_jobs = [
                    visier_platform_sdk.models.data_in/receiving_job.data_in.ReceivingJob(
                        receiving_job_id = '', 
                        tenant_code = '', 
                        status = '', )
                    ]
            )
        else:
            return DataInReceivingJobStatusResponse(
        )
        """

    def testDataInReceivingJobStatusResponse(self):
        """Test DataInReceivingJobStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
