# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.dataservices_query_snapshot_query_execution_dto import DataservicesQuerySnapshotQueryExecutionDTO

class TestDataservicesQuerySnapshotQueryExecutionDTO(unittest.TestCase):
    """DataservicesQuerySnapshotQueryExecutionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataservicesQuerySnapshotQueryExecutionDTO:
        """Test DataservicesQuerySnapshotQueryExecutionDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataservicesQuerySnapshotQueryExecutionDTO`
        """
        model = DataservicesQuerySnapshotQueryExecutionDTO()
        if include_optional:
            return DataservicesQuerySnapshotQueryExecutionDTO(
                source = visier_platform_sdk.models.dataservices/query/list_query_source_dto.dataservices.query.ListQuerySourceDTO(
                    formula = '', 
                    metric = '', 
                    analytic_object = '', 
                    text_concept = '', ),
                columns = [
                    visier_platform_sdk.models.dataservices/query/property_column_dto.dataservices.query.PropertyColumnDTO(
                        column_name = '', 
                        column_definition = None, )
                    ],
                sort_options = [
                    visier_platform_sdk.models.dataservices/query/sort_option_dto.dataservices.query.SortOptionDTO(
                        column_index = 56, 
                        sort_direction = 'SORT_ASCENDING', )
                    ],
                filters = [
                    visier_platform_sdk.models.dataservices/query/query_filter_dto.dataservices.query.QueryFilterDTO(
                        formula = '', 
                        selection_concept = None, 
                        member_set = None, 
                        cohort = None, )
                    ],
                time_intervals = visier_platform_sdk.models.dataservices/query/query_time_intervals_dto.dataservices.query.QueryTimeIntervalsDTO(
                    from_instant = '', 
                    from_date_time = '', 
                    dynamic_date_from = 'SOURCE', 
                    interval_period_type = 'MONTH', 
                    interval_period_count = 56, 
                    interval_count = 56, 
                    direction = 'BACKWARD', 
                    shift = None, 
                    trailing_period_type = 'MONTH', 
                    trailing_period_count = 56, ),
                parameter_values = [
                    visier_platform_sdk.models.dataservices/query/query_parameter_value_dto.dataservices.query.QueryParameterValueDTO(
                        member_value = None, 
                        numeric_value = None, 
                        plan_value = None, 
                        aggregation_type_value = None, )
                    ],
                options = visier_platform_sdk.models.dataservices/query/snapshot_query_execution_options_dto.dataservices.query.SnapshotQueryExecutionOptionsDTO(
                    limit = 56, 
                    query_mode = 'DEFAULT', 
                    omit_header = True, 
                    calendar_type = 'TENANT_CALENDAR', 
                    currency_conversion_date = '', 
                    page = 56, 
                    multiple_tables = True, 
                    currency_conversion_code = '', 
                    date_time_display_mode = 'EPOCH', )
            )
        else:
            return DataservicesQuerySnapshotQueryExecutionDTO(
        )
        """

    def testDataservicesQuerySnapshotQueryExecutionDTO(self):
        """Test DataservicesQuerySnapshotQueryExecutionDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
