# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.servicing_objectconfiguration_property_delete_success_dto import ServicingObjectconfigurationPropertyDeleteSuccessDTO

class TestServicingObjectconfigurationPropertyDeleteSuccessDTO(unittest.TestCase):
    """ServicingObjectconfigurationPropertyDeleteSuccessDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServicingObjectconfigurationPropertyDeleteSuccessDTO:
        """Test ServicingObjectconfigurationPropertyDeleteSuccessDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServicingObjectconfigurationPropertyDeleteSuccessDTO`
        """
        model = ServicingObjectconfigurationPropertyDeleteSuccessDTO()
        if include_optional:
            return ServicingObjectconfigurationPropertyDeleteSuccessDTO(
                id = '',
                display_name = '',
                tenant_code = '',
                project_id = '',
                derived_dependents_deleted = [
                    visier_platform_sdk.models.servicing/objectconfiguration/dependent_dto.servicing.objectconfiguration.DependentDTO(
                        id = '', 
                        display_name = '', 
                        object_type = '', )
                    ],
                reference_dependents_ignored = [
                    visier_platform_sdk.models.servicing/objectconfiguration/dependent_dto.servicing.objectconfiguration.DependentDTO(
                        id = '', 
                        display_name = '', 
                        object_type = '', )
                    ]
            )
        else:
            return ServicingObjectconfigurationPropertyDeleteSuccessDTO(
        )
        """

    def testServicingObjectconfigurationPropertyDeleteSuccessDTO(self):
        """Test ServicingObjectconfigurationPropertyDeleteSuccessDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
