# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.planning_get_plan_list_response_dto import PlanningGetPlanListResponseDTO

class TestPlanningGetPlanListResponseDTO(unittest.TestCase):
    """PlanningGetPlanListResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanningGetPlanListResponseDTO:
        """Test PlanningGetPlanListResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlanningGetPlanListResponseDTO`
        """
        model = PlanningGetPlanListResponseDTO()
        if include_optional:
            return PlanningGetPlanListResponseDTO(
                plans = [
                    visier_platform_sdk.models.planning/plan_info_dto.planning.PlanInfoDTO(
                        uuid = '', 
                        display_name = '', 
                        model_id = '', 
                        scenarios = [
                            visier_platform_sdk.models.planning/scenario_info_dto.planning.ScenarioInfoDTO(
                                uuid = '', 
                                display_name = '', 
                                versioned_scenario_id = '', )
                            ], 
                        parent_plan_uuid = '', 
                        currency_code = '', )
                    ],
                page = 56
            )
        else:
            return PlanningGetPlanListResponseDTO(
        )
        """

    def testPlanningGetPlanListResponseDTO(self):
        """Test PlanningGetPlanListResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
