# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.designer_data_version_exports_dto import DesignerDataVersionExportsDTO

class TestDesignerDataVersionExportsDTO(unittest.TestCase):
    """DesignerDataVersionExportsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DesignerDataVersionExportsDTO:
        """Test DesignerDataVersionExportsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DesignerDataVersionExportsDTO`
        """
        model = DesignerDataVersionExportsDTO()
        if include_optional:
            return DesignerDataVersionExportsDTO(
                data_version_exports = [
                    visier_platform_sdk.models.designer/data_version_export_dto.designer.DataVersionExportDTO(
                        uuid = '', 
                        timestamp = '', 
                        data_version_number = '', 
                        base_data_version_number = '', 
                        tables = [
                            visier_platform_sdk.models.designer/data_version_export_table_dto.designer.DataVersionExportTableDTO(
                                name = '', 
                                common_columns = None, 
                                new_columns = None, 
                                deleted_columns = [
                                    ''
                                    ], )
                            ], 
                        new_tables = [
                            ''
                            ], 
                        deleted_tables = [
                            ''
                            ], )
                    ]
            )
        else:
            return DesignerDataVersionExportsDTO(
        )
        """

    def testDesignerDataVersionExportsDTO(self):
        """Test DesignerDataVersionExportsDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
