# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.2341
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import visier_platform_sdk.models
from visier_platform_sdk.models.webhook_details_dto import WebhookDetailsDTO

class TestWebhookDetailsDTO(unittest.TestCase):
    """WebhookDetailsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookDetailsDTO:
        """Test WebhookDetailsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """

        if include_optional:
            return WebhookDetailsDTO(
                target_url = '',
                is_active = True,
                events = [
                    visier_platform_sdk.models.webhook_event_type_dto.WebhookEventTypeDTO(
                        event_type = '', )
                    ],
                key_name = '',
                display_name = ''
            )
        else:
            return WebhookDetailsDTO(
        )

    def testWebhookDetailsDTO(self):
        """Test WebhookDetailsDTO"""
        def validate_instance(instance):
            WebhookDetailsDTO.model_validate(inst_req_only)
            instance_deserialized = WebhookDetailsDTO.from_dict(instance.to_dict())
            assert instance == instance_deserialized

        inst_req_only = self.make_instance(include_optional=False)
        validate_instance(inst_req_only)

        inst_req_and_optional = self.make_instance(include_optional=True)
        validate_instance(inst_req_and_optional)

if __name__ == '__main__':
    unittest.main()
