# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.2341
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import visier_platform_sdk.models
from visier_platform_sdk.models.vee_question_change_failure_dto import VeeQuestionChangeFailureDTO

class TestVeeQuestionChangeFailureDTO(unittest.TestCase):
    """VeeQuestionChangeFailureDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VeeQuestionChangeFailureDTO:
        """Test VeeQuestionChangeFailureDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """

        if include_optional:
            return VeeQuestionChangeFailureDTO(
                question = '',
                question_id = '',
                category_id = '',
                user_group_assignment = visier_platform_sdk.models.user_group_assignment_dto.UserGroupAssignmentDTO(
                    user_group_ids = [
                        ''
                        ], ),
                message = '',
                rci = '',
                tenant_code = '',
                project_id = ''
            )
        else:
            return VeeQuestionChangeFailureDTO(
        )

    def testVeeQuestionChangeFailureDTO(self):
        """Test VeeQuestionChangeFailureDTO"""
        def validate_instance(instance):
            VeeQuestionChangeFailureDTO.model_validate(inst_req_only)
            instance_deserialized = VeeQuestionChangeFailureDTO.from_dict(instance.to_dict())
            assert instance == instance_deserialized

        inst_req_only = self.make_instance(include_optional=False)
        validate_instance(inst_req_only)

        inst_req_and_optional = self.make_instance(include_optional=True)
        validate_instance(inst_req_and_optional)

if __name__ == '__main__':
    unittest.main()
