# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.1892
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from visier_platform_sdk.models.admin_user_groups_users_for_tenant_dto import AdminUserGroupsUsersForTenantDTO

class TestAdminUserGroupsUsersForTenantDTO(unittest.TestCase):
    """AdminUserGroupsUsersForTenantDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminUserGroupsUsersForTenantDTO:
        """Test AdminUserGroupsUsersForTenantDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminUserGroupsUsersForTenantDTO`
        """
        model = AdminUserGroupsUsersForTenantDTO()
        if include_optional:
            return AdminUserGroupsUsersForTenantDTO(
                tenant_code = '',
                users = [
                    visier_platform_sdk.models.admin/simple_user_dto.admin.SimpleUserDTO(
                        user_id = '', 
                        username = '', )
                    ]
            )
        else:
            return AdminUserGroupsUsersForTenantDTO(
        )
        """

    def testAdminUserGroupsUsersForTenantDTO(self):
        """Test AdminUserGroupsUsersForTenantDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
