# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.2341
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import visier_platform_sdk.models
from visier_platform_sdk.models.data_security_profile_dto import DataSecurityProfileDTO

class TestDataSecurityProfileDTO(unittest.TestCase):
    """DataSecurityProfileDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataSecurityProfileDTO:
        """Test DataSecurityProfileDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """

        if include_optional:
            return DataSecurityProfileDTO(
                analytic_object_id = '',
                property_set_config = visier_platform_sdk.models.property_set_config_dto.PropertySetConfigDTO(
                    property_access_configs = [
                        visier_platform_sdk.models.property_access_config_dto.PropertyAccessConfigDTO(
                            property_id = '', 
                            analytic_object_id = '', 
                            analytic_object_reference_paths = [
                                ''
                                ], 
                            access_level = 'None', 
                            property_status = 'Unset', )
                        ], 
                    shareable_data_access_set = None, ),
                all_data_point_access = True,
                member_filter_configs = [
                    visier_platform_sdk.models.member_filter_config_dto.MemberFilterConfigDTO(
                        dimension_filters = [
                            visier_platform_sdk.models.dimension_filter_dto.DimensionFilterDTO(
                                dimension_name = '', 
                                qualifying_path = [
                                    ''
                                    ], 
                                member_selections = [
                                    visier_platform_sdk.models.member_selection_dto.MemberSelectionDTO(
                                        name_path = [
                                            ''
                                            ], 
                                        is_excluded = True, )
                                    ], )
                            ], )
                    ],
                inherited_access_configs = [
                    visier_platform_sdk.models.inherited_access_config_dto.InheritedAccessConfigDTO(
                        analytic_object_id = '', 
                        remove_access = True, 
                        member_filter_configs = [
                            visier_platform_sdk.models.member_filter_config_dto.MemberFilterConfigDTO(
                                dimension_filters = [
                                    visier_platform_sdk.models.dimension_filter_dto.DimensionFilterDTO(
                                        dimension_name = '', 
                                        qualifying_path = [
                                            ''
                                            ], 
                                        member_selections = [
                                            visier_platform_sdk.models.member_selection_dto.MemberSelectionDTO(
                                                name_path = [
                                                    ''
                                                    ], 
                                                is_excluded = True, )
                                            ], )
                                    ], )
                            ], )
                    ],
                inherited_reference_member_filter_config = visier_platform_sdk.models.inherited_reference_member_filter_config_dto.InheritedReferenceMemberFilterConfigDTO(
                    target_analytic_object_id = '', 
                    analytic_object_reference = '', ),
                analytic_object_status = 'Unset'
            )
        else:
            return DataSecurityProfileDTO(
        )

    def testDataSecurityProfileDTO(self):
        """Test DataSecurityProfileDTO"""
        def validate_instance(instance):
            DataSecurityProfileDTO.model_validate(inst_req_only)
            instance_deserialized = DataSecurityProfileDTO.from_dict(instance.to_dict())
            assert instance == instance_deserialized

        inst_req_only = self.make_instance(include_optional=False)
        validate_instance(inst_req_only)

        inst_req_and_optional = self.make_instance(include_optional=True)
        validate_instance(inst_req_and_optional)

if __name__ == '__main__':
    unittest.main()
