# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.2341
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import visier_platform_sdk.models
from visier_platform_sdk.models.selection_concepts_dto import SelectionConceptsDTO

class TestSelectionConceptsDTO(unittest.TestCase):
    """SelectionConceptsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SelectionConceptsDTO:
        """Test SelectionConceptsDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """

        if include_optional:
            return SelectionConceptsDTO(
                selection_concepts = [
                    visier_platform_sdk.models.selection_concept_dto.SelectionConceptDTO(
                        id = '', 
                        display_name = '', 
                        description = '', 
                        visible_in_app = True, 
                        tags = [
                            visier_platform_sdk.models.tag_map_element_dto.TagMapElementDTO(
                                id = '', 
                                display_name = '', )
                            ], 
                        explanation = '', )
                    ]
            )
        else:
            return SelectionConceptsDTO(
        )

    def testSelectionConceptsDTO(self):
        """Test SelectionConceptsDTO"""
        def validate_instance(instance):
            SelectionConceptsDTO.model_validate(inst_req_only)
            instance_deserialized = SelectionConceptsDTO.from_dict(instance.to_dict())
            assert instance == instance_deserialized

        inst_req_only = self.make_instance(include_optional=False)
        validate_instance(inst_req_only)

        inst_req_and_optional = self.make_instance(include_optional=True)
        validate_instance(inst_req_and_optional)

if __name__ == '__main__':
    unittest.main()
