# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.2341
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import visier_platform_sdk.models
from visier_platform_sdk.models.property_definition_dto import PropertyDefinitionDTO

class TestPropertyDefinitionDTO(unittest.TestCase):
    """PropertyDefinitionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PropertyDefinitionDTO:
        """Test PropertyDefinitionDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """

        if include_optional:
            return PropertyDefinitionDTO(
                uuid = '',
                object_name = '',
                basic_information = visier_platform_sdk.models.basic_information_dto.BasicInformationDTO(
                    display_name = '', 
                    short_display_name = '', 
                    description = '', 
                    explanation = '', 
                    designer_notes = '', 
                    synonym_list = None, ),
                details = visier_platform_sdk.models.property_type_details_dto.PropertyTypeDetailsDTO(
                    simple = None, 
                    calculated = None, 
                    multi_value = None, ),
                tag_list = visier_platform_sdk.models.tag_reference_list_dto.TagReferenceListDTO(
                    tags = [
                        visier_platform_sdk.models.tag_reference_dto.TagReferenceDTO(
                            object_name = '', )
                        ], ),
                include_with_vee = True,
                version_information = visier_platform_sdk.models.version_information_dto.VersionInformationDTO(
                    version_type = 'Unknown', 
                    edited = '', 
                    editor = '', )
            )
        else:
            return PropertyDefinitionDTO(
        )

    def testPropertyDefinitionDTO(self):
        """Test PropertyDefinitionDTO"""
        def validate_instance(instance):
            PropertyDefinitionDTO.model_validate(inst_req_only)
            instance_deserialized = PropertyDefinitionDTO.from_dict(instance.to_dict())
            assert instance == instance_deserialized

        inst_req_only = self.make_instance(include_optional=False)
        validate_instance(inst_req_only)

        inst_req_and_optional = self.make_instance(include_optional=True)
        validate_instance(inst_req_and_optional)

if __name__ == '__main__':
    unittest.main()
