# coding: utf-8

"""
    API Reference

    Detailed API reference documentation for Visier APIs. Includes all endpoints, headers, path parameters, query parameters, request body schema, response schema, JSON request samples, and JSON response samples.

    The version of the OpenAPI document: 22222222.99201.2341
    Contact: alpine@visier.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import visier_platform_sdk.models
from visier_platform_sdk.models.sql_like_query_execution_dto import SqlLikeQueryExecutionDTO

class TestSqlLikeQueryExecutionDTO(unittest.TestCase):
    """SqlLikeQueryExecutionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SqlLikeQueryExecutionDTO:
        """Test SqlLikeQueryExecutionDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """

        if include_optional:
            return SqlLikeQueryExecutionDTO(
                query = '',
                options = visier_platform_sdk.models.aggregate_query_execution_options_dto.AggregateQueryExecutionOptionsDTO(
                    calendar_type = 'TENANT_CALENDAR', 
                    currency_conversion_mode = 'TENANT_CURRENCY_CONVERSION', 
                    currency_conversion_date = '', 
                    lineage_depth = 56, 
                    zero_visibility = 'SHOW', 
                    null_visibility = 'SHOW', 
                    cell_distribution_options = visier_platform_sdk.models.cell_distribution_options_dto.CellDistributionOptionsDTO(
                        bin_count = 56, ), 
                    axis_visibility = 'SIMPLE', 
                    enable_sparse_results = True, 
                    internal = visier_platform_sdk.models.internal_query_execution_options_dto.InternalQueryExecutionOptionsDTO(
                        sparse_handling_mode = 'ALLOW', 
                        align_time_axis_to_period_end = True, ), 
                    enable_descending_space = True, 
                    currency_conversion_code = '', 
                    member_display_mode = 'DEFAULT', 
                    axes_overall_value_mode = 'NONE', ),
                aggregate_query_options = visier_platform_sdk.models.aggregate_query_execution_options_dto.AggregateQueryExecutionOptionsDTO(
                    calendar_type = 'TENANT_CALENDAR', 
                    currency_conversion_mode = 'TENANT_CURRENCY_CONVERSION', 
                    currency_conversion_date = '', 
                    lineage_depth = 56, 
                    zero_visibility = 'SHOW', 
                    null_visibility = 'SHOW', 
                    cell_distribution_options = visier_platform_sdk.models.cell_distribution_options_dto.CellDistributionOptionsDTO(
                        bin_count = 56, ), 
                    axis_visibility = 'SIMPLE', 
                    enable_sparse_results = True, 
                    internal = visier_platform_sdk.models.internal_query_execution_options_dto.InternalQueryExecutionOptionsDTO(
                        sparse_handling_mode = 'ALLOW', 
                        align_time_axis_to_period_end = True, ), 
                    enable_descending_space = True, 
                    currency_conversion_code = '', 
                    member_display_mode = 'DEFAULT', 
                    axes_overall_value_mode = 'NONE', ),
                list_query_options = visier_platform_sdk.models.list_query_execution_options_dto.ListQueryExecutionOptionsDTO(
                    limit = 56, 
                    query_mode = 'DEFAULT', 
                    omit_header = True, 
                    calendar_type = 'TENANT_CALENDAR', 
                    currency_conversion_mode = 'TENANT_CURRENCY_CONVERSION', 
                    currency_conversion_date = '', 
                    page = 56, 
                    multiple_tables = True, 
                    currency_conversion_code = '', 
                    record_mode = 'NORMAL', 
                    date_time_display_mode = 'EPOCH', )
            )
        else:
            return SqlLikeQueryExecutionDTO(
        )

    def testSqlLikeQueryExecutionDTO(self):
        """Test SqlLikeQueryExecutionDTO"""
        def validate_instance(instance):
            SqlLikeQueryExecutionDTO.model_validate(inst_req_only)
            instance_deserialized = SqlLikeQueryExecutionDTO.from_dict(instance.to_dict())
            assert instance == instance_deserialized

        inst_req_only = self.make_instance(include_optional=False)
        validate_instance(inst_req_only)

        inst_req_and_optional = self.make_instance(include_optional=True)
        validate_instance(inst_req_and_optional)

if __name__ == '__main__':
    unittest.main()
