name: Publish Python SDK to PyPI

on:
  workflow_dispatch:
    inputs:
      publish_branch:
        required: true
        description: 'Branch to publish from'

  pull_request:
    branches:
      - feature/VAN-122988-test

jobs:
  publish_package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-dir:
          - src/visier.sdk.api.model_query
          # Add more package directories as needed

    steps:
      - name: Determine branch
        id: determine-branch
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "BRANCH=${{ github.event.inputs.publish_branch }}" >> $GITHUB_ENV
          else
            echo "Error: Unsupported event type '${{ github.event_name }}'"
            exit 1
          fi

      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build and publish packages
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          cd ${{ matrix.package-dir }}
          python setup.py sdist bdist_wheel
          python -m twine upload dist/*

      - name: Merge PR
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch