name: Publish Python SDK to PyPI

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
      - github-actions-test

# Permissions to create PR, to write changes, to use PyPi auth
permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  publish_package:
    if: startsWith(github.head_ref, 'release')
    name: Publish Python SDK to PyPI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - visier.sdk.api.administration
          - visier.sdk.api.analytic_model
          - visier.sdk.api.data_in
          - visier.sdk.api.data_out

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build

      - name: Build package
        run: |
          cd "src/${{ matrix.package }}"
          python -m build --outdir ./dist

      - name: Publish PyPi package
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          packages-dir: "src/${{ matrix.package }}/dist"

  merge_pr:
    needs: publish_package
    if: needs.publish_package.result == 'success'
    name: Merge PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out before merge
        uses: actions/checkout@v4

      - name: Merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch