name: Publish Python SDK to PyPI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - main
      - github-actions-test

# Required to publish packages to PyPI
permissions:
  contents: read
  id-token: write

jobs:
  publish_package:
    name: Publish Python SDK to PyPI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-dir:
          - src/visier.sdk.api.administration
          - src/visier.sdk.api.analytic_model
          - src/visier.sdk.api.data_in
          - src/visier.sdk.api.data_out

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build

      - name: Build package
        run: |
          cd ${{ matrix.package-dir }}
          python -m build

      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          packages-dir: ${{ matrix.package-dir }}

  merge_pr:
    needs: publish_package
    name: Merge PR
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' }}
    steps:
      - name: Check out before merge
        uses: actions/checkout@v4

      - name: Merge PR
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch